/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package unid;

import Splash.ImagenDeFondo;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.IOException;
import java.util.Random;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author jonatan
 */
public class MainForm extends javax.swing.JFrame {

    TablaExcel tabla = new TablaExcel();
    DropExcel dp;
    ImagenDeFondo fondo = new ImagenDeFondo("/Splash/Unid_conecta.png");
    ImagenDeFondo modelos;
    public MainForm() {
       // setFondo();
        setContentPane(fondo);//si pongo el metodo antes se vera como un fondo
        initComponents();
        setLocationRelativeTo(null);
        Enablef();
        jPanel1.setBackground(new Color(0, 0, 0, 5));
        enableHomeF();
        MenuInformacion.setText("Información");
        
    }
    
   
    public void setFondo(){
        String arr[]  = new String[]{"Unid_conecta.png","adm.jpg","comunicacion.jpg","lic_sis.jpg"};
        Random img = new Random();
        int x = img.nextInt(arr.length-1);
        String aux = arr[x].toString();
        System.out.println(""+aux);
        modelos = new ImagenDeFondo("/Splash/"+aux);
        setContentPane(modelos);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuHome = new javax.swing.JMenuItem();
        MenuImportar = new javax.swing.JMenuItem();
        MenuExportar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MenuGuardar = new javax.swing.JMenuItem();
        MenuMostrar = new javax.swing.JMenuItem();
        MenuBuscar = new javax.swing.JMenuItem();
        MenuIdentificar = new javax.swing.JMenuItem();
        MenuItem = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        MenuInformacion = new javax.swing.JMenuItem();
        MenuAyuda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 738, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 428, Short.MAX_VALUE)
        );

        jMenuBar1.setBorder(null);
        jMenuBar1.setForeground(new java.awt.Color(0, 51, 153));
        jMenuBar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jMenuBar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jMenuBar1MouseExited(evt);
            }
        });

        jMenu1.setText("File");
        jMenu1.setContentAreaFilled(false);
        jMenu1.setFocusable(false);
        jMenu1.setRequestFocusEnabled(false);

        MenuHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/inicio.png"))); // NOI18N
        MenuHome.setText("Home");
        MenuHome.setContentAreaFilled(false);
        MenuHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuHomeActionPerformed(evt);
            }
        });
        jMenu1.add(MenuHome);

        MenuImportar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/excel-xls-icon46x46.png"))); // NOI18N
        MenuImportar.setText("Importar");
        MenuImportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuImportarActionPerformed(evt);
            }
        });
        jMenu1.add(MenuImportar);

        MenuExportar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/pdf-icon64x64.png"))); // NOI18N
        MenuExportar.setText("Exportar");
        MenuExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuExportarActionPerformed(evt);
            }
        });
        jMenu1.add(MenuExportar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenu2.setEnabled(false);

        MenuGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/04-Save-icon.png"))); // NOI18N
        MenuGuardar.setText("Guardar");
        MenuGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuGuardarActionPerformed(evt);
            }
        });
        jMenu2.add(MenuGuardar);

        MenuMostrar.setText("Mostrar");
        MenuMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuMostrarActionPerformed(evt);
            }
        });
        jMenu2.add(MenuMostrar);

        MenuBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/buscarL.png"))); // NOI18N
        MenuBuscar.setText("Buscar");
        MenuBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuBuscarActionPerformed(evt);
            }
        });
        jMenu2.add(MenuBuscar);

        MenuIdentificar.setText("Identificar");
        MenuIdentificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuIdentificarActionPerformed(evt);
            }
        });
        jMenu2.add(MenuIdentificar);

        MenuItem.setText("null");
        MenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(MenuItem);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("navegacion");

        jMenuItem5.setText("Informacion");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Ayuda?");

        MenuInformacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/info.png"))); // NOI18N
        MenuInformacion.setText("InformaciÃ³n");
        jMenu4.add(MenuInformacion);

        MenuAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/ayuda.png"))); // NOI18N
        MenuAyuda.setText("Ayuda?");
        MenuAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAyudaActionPerformed(evt);
            }
        });
        jMenu4.add(MenuAyuda);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
      public void Enablet(){
      jMenu2.setEnabled(true);
      //jMenu3.setEnabled(true);
        MenuBuscar.setEnabled(true);
        MenuGuardar.setEnabled(true);
        MenuItem.setEnabled(true);
        MenuIdentificar.setEnabled(true);
        MenuMostrar.setEnabled(true);
      }
      public void Enablef(){
        jMenu2.setEnabled(false);
      //   jMenu3.setEnabled(false);
        MenuBuscar.setEnabled(false);
        MenuGuardar.setEnabled(false);
        MenuItem.setEnabled(false);
        MenuIdentificar.setEnabled(false);
        MenuMostrar.setEnabled(false);
      }
      public void enableHome(){
          MenuImportar.setEnabled(true);
         MenuExportar.setEnabled(true);
      }
      public void enableHomeF(){
          MenuImportar.setEnabled(false);
          MenuExportar.setEnabled(false);
      }
    private void MenuHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuHomeActionPerformed
        int W = jPanel1.getWidth();
        int H = jPanel1.getHeight();
        tabla.setPreferredSize(new Dimension(W, H));
        new explode(jPanel1, tabla).play();
        jPanel1.updateUI();
        jPanel1.validate();
        Enablet();
        enableHome();
    }//GEN-LAST:event_MenuHomeActionPerformed
    public void CerrarVentana(){
        try {
           this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            addWindowListener(new WindowAdapter() {
            public void WindowClosing(WindowEvent e)    {
                confirmarSalida();
              //System.out.println("Boton");
            }
        });
           this.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    public void confirmarSalida(){
        int valor = JOptionPane.showConfirmDialog(this, "Estas seguro de salir","advertencia",JOptionPane.YES_NO_OPTION,JOptionPane.CLOSED_OPTION);
        if (valor == JOptionPane.YES_OPTION) {
            System.exit(0);
            }
    }
    private void jMenuBar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuBar1MouseEntered
       
    }//GEN-LAST:event_jMenuBar1MouseEntered

    private void jMenuBar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuBar1MouseExited
       
    }//GEN-LAST:event_jMenuBar1MouseExited

    private void MenuGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuGuardarActionPerformed
      //tabla.setGuardar();
       tabla.setExclusive();
    }//GEN-LAST:event_MenuGuardarActionPerformed

    private void MenuMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuMostrarActionPerformed
      tabla.setMostrar();
     
    }//GEN-LAST:event_MenuMostrarActionPerformed

    private void MenuBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuBuscarActionPerformed
      tabla.setBuscar();
    }//GEN-LAST:event_MenuBuscarActionPerformed

    private void MenuIdentificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuIdentificarActionPerformed
        tabla.setIdentyColors();
    }//GEN-LAST:event_MenuIdentificarActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
    try {
        File path = new File ("C:\\Users\\jonatan\\Documents\\NetBeansProjects\\c++\\Unid\\src\\pdf\\lsi.pdf");
        Desktop.getDesktop().open(path);
        System.out.println("Se abrio correctamente.");
        }catch (IOException ex) {
        ex.printStackTrace();
    }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void MenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemActionPerformed
       tabla.getGuardar();
    }//GEN-LAST:event_MenuItemActionPerformed

    private void MenuImportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuImportarActionPerformed
        try{
        List listaPariticipante = new ArrayList();

        for (int i = 1; i <= 10; i++) 
        {
            Materias p = new Materias( i,"Particpante " + i, "Usuario " + i); 
            listaPariticipante.add(p);
        } 
        JasperReport reporte = (JasperReport) JRLoader.loadObject("reporte2.jasper");
        
        Map parametros = new HashMap<String,String>();
        parametros.put("titulo", "Ejemplo de JasperReports");
        parametros.put("autor", "Jonatan Lara");
        JasperPrint jasperPrint = JasperFillManager.fillReport(reporte,parametros, new JRBeanCollectionDataSource(listaPariticipante));
            JasperViewer view = new JasperViewer(jasperPrint,false);
            view.setTitle("Reporte de  ");
            view.setVisible(true);
            JOptionPane.showMessageDialog(null, "Operacion Exitosa");
        }catch(JRException e){
            System.out.println("mensaje"+e);
        }
    }//GEN-LAST:event_MenuImportarActionPerformed

    private void MenuExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuExportarActionPerformed
       tabla.setImprimir();
    }//GEN-LAST:event_MenuExportarActionPerformed

    private void MenuAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAyudaActionPerformed
        tabla.setAbrirAyuda("C:\\Users\\jonatan\\Documents\\NetBeansProjects\\c++\\Unid\\src\\internet\\javaHelp\\index.html");
    }//GEN-LAST:event_MenuAyudaActionPerformed
   
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
         
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuAyuda;
    private javax.swing.JMenuItem MenuBuscar;
    private javax.swing.JMenuItem MenuExportar;
    private javax.swing.JMenuItem MenuGuardar;
    private javax.swing.JMenuItem MenuHome;
    private javax.swing.JMenuItem MenuIdentificar;
    private javax.swing.JMenuItem MenuImportar;
    private javax.swing.JMenuItem MenuInformacion;
    private javax.swing.JMenuItem MenuItem;
    private javax.swing.JMenuItem MenuMostrar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
