/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package unid;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jonatan
 */
public class TablaExcel extends javax.swing.JPanel {

    private DefaultTableModel model;
    //public static int con = 0;
    ArrayList <Object>listas = new ArrayList<Object>();
  //  public ArrayList listasr = new ArrayList();
    DropExcel drop;
    public TablaExcel() {
        
         initComponents();
         
         TablaDatos.updateUI();
         TablaDatos.validate();
         drop = new DropExcel(TablaDatos);
         
         
         //TablaDatos.setPreferredSize(null);
       
    }
   /* public Object getGuardar(){
        for (int i = 0; i < TablaDatos.getColumnCount(); i++) {
            for (int j = 0; j < TablaDatos.getRowCount(); j++) {
                listas.add(model.getValueAt(i, j).toString());
                
            }
        }
        System.out.println("Se guardaron los datos");
        return listas;
    }**/
    public void recorrer(){
        for (int i = 0; i < TablaDatos.getRowCount(); i++) {
            for (int j = 0; j < TablaDatos.getColumnCount(); j++) {
               TablaDatos.setBackground(new Color(0, 0, 0, 15));
                jScrollPane1.setBackground(new Color(0, 0, 0, 15));
                
            }
            
        }
    
    }
    public void getGuardar(){
        drop.getguardar();
        
    }
    public void setGuardar(){
        drop.guardar();
        
    }
    public void setMostrar(){
        drop.mostrar();
    }
    public void setBuscar(){
        drop.Buscar();
    }
    public void setIdentyColors(){
        drop.identyColors();
    }
   public void setImprimir(){
        drop.imprimir();
   }
   public void setExclusive(){
        drop.exclusive();
   }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaDatos = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(738, 426));

        TablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaDatos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaDatos;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
